# Generated by Django 6.0.3 on 2026-04-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0003_siteconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")],
                default="success",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="target_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="target_public_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("check_pending", "Check Pending"),
                    ("follow_up", "Follow Up"),
                    ("send_message", "Send Message"),
                ],
                max_length=20,
            ),
        ),
    ]
