# Generated by Django 5.2.12 on 2026-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0004_actionlog_note_actionlog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_freemium',
            field=models.BooleanField(default=False, help_text='Uses a pre-trained kit model instead of active learning. Optimized for standard hiring/sales personas.'),
        ),
    ]
