# Generated by Django 5.2.12 on 2026-04-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_deal_state_alter_lead_disqualified'),
        ('linkedin', '0005_alter_campaign_is_freemium'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='The deal this task targets (allows fast indexing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal'),
        ),
    ]
