# Generated by Django 5.2.12 on 2026-04-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_deal_state_alter_lead_disqualified'),
        ('linkedin', '0006_task_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='model_blob',
        ),
        migrations.AlterField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='The deal this task targets (allows fast indexing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.deal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
