# Generated by Django 6.0.5 on 2026-08-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0023_rename_after_invite_confidence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='actionlog',
            name='linkedin_ac_linkedi_37318d_idx',
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('send_message', 'Send Message'), ('reply_check', 'Reply Check')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('send_message', 'Send Message'), ('reply_check', 'Reply Check')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['instagram_profile', 'action_type', 'created_at'], name='linkedin_ac_instagr_b2a599_idx'),
        ),
    ]
