# Generated by Django 6.0.5 on 2026-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0024_remove_actionlog_linkedin_ac_linkedi_37318d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachevent',
            name='event_type',
            field=models.CharField(choices=[('follow_sent', 'Follow Sent'), ('follow_failed', 'Follow Failed'), ('follow_back_detected', 'Follow Back Detected'), ('message_sent', 'Message Sent'), ('message_failed', 'Message Failed')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='pause_new_follows',
            field=models.BooleanField(default=False, help_text='Stops new top-of-funnel outreach expansion (discover → qualify → DM draft). Existing drafts, approvals, sends, reply checks, and follow-up bumps continue.'),
        ),
    ]
