# Generated by Django 5.2.12 on 2026-04-10 12:37

import linkedin.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_public_identifier_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Pending', 'Pending'), ('Connected', 'Connected'), ('Completed', 'Completed'), ('Failed', 'Failed')], default=linkedin.enums.ProfileState['QUALIFIED'], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='disqualified',
            field=models.BooleanField(default=False, help_text="PERMANENT GLOBAL BAN. If set, this person will NEVER be contacted again by ANY campaign. For campaign-specific disqualification, use the Deal's closing reason instead."),
        ),
    ]
