# Generated by Django 5.2.12 on 2026-04-11 06:30

import django.db.models.deletion
import django.utils.timezone
import linkedin.enums
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_deal_state_alter_lead_disqualified'),
        ('linkedin', '0007_remove_campaign_model_blob_alter_task_deal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDeal',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.CharField(choices=[('Qualified', 'Qualified'), ('Pending', 'Pending'), ('Connected', 'Connected'), ('Completed', 'Completed'), ('Failed', 'Failed')], default=linkedin.enums.ProfileState['QUALIFIED'], max_length=20)),
                ('closing_reason', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('Disqualified', 'Disqualified')], default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('connect_attempts', models.IntegerField(default=0)),
                ('backoff_hours', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='linkedin.campaign')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.lead')),
            ],
            options={
                'verbose_name': 'historical Deal',
                'verbose_name_plural': 'historical Deals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLead',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('linkedin_url', models.URLField(db_index=True)),
                ('public_identifier', models.CharField(db_index=True, max_length=200)),
                ('profile_data', models.JSONField(blank=True, default=None, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('disqualified', models.BooleanField(default=False, help_text="PERMANENT GLOBAL BAN. If set, this person will NEVER be contacted again by ANY campaign. For campaign-specific disqualification, use the Deal's closing reason instead.")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lead',
                'verbose_name_plural': 'historical Leads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
