# Generated by Django 5.2.12 on 2026-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_historicaldeal_historicallead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='profile_data',
        ),
    ]
