# Generated by Django 6.0.3 on 2026-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_add_linkedin_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="True if the admin has approved this drafted message to be sent",
                verbose_name="Is Approved",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="True if the message is drafted by AI and waiting for approval",
                verbose_name="Is Draft",
            ),
        ),
    ]
