# Generated by Django 5.2.12 on 2026-04-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_is_approved_chatmessage_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='answer_to',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='to',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='topic',
        ),
    ]
