# Generated by Django 5.2.12 on 2026-04-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmessage_answer_to_and_more'),
        ('linkedin', '0006_task_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='linkedin.campaign', verbose_name='Campaign'),
        ),
    ]
