# Generated by Django 6.0.4 on 2026-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0009_siteconfig_google_sheet_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='google_sheet_id',
            field=models.CharField(blank=True, default='', help_text='Paste the full Google Sheets browser URL or the bare spreadsheet id (saved as id only).', max_length=128),
        ),
    ]
