# Generated by Django 6.0.4 on 2026-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0010_alter_siteconfig_google_sheet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="azure_api_version",
            field=models.CharField(blank=True, default="2024-10-21", max_length=50),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="azure_deployment",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="llm_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI Compatible"),
                    ("azure", "Azure OpenAI / Foundry"),
                    ("gemini", "Google Gemini"),
                ],
                default="openai",
                max_length=20,
            ),
        ),
    ]
